### ISSUE TITLE
Release tarball

### ISSUE THREAD

**Issue by fabaff** [bonsaiviking/NfSpy#1]
For packaging nfspy for distributions it would make things easier if there is a source tarball. Can you please make such tarball available [1]? 

Thanks in advance

[1] https://github.com/blog/1547-release-your-software

**Comment by bonsaiviking** [comment]
@fabaff Thanks for pointing this out. I hadn't heard of Github's "releases" feature yet, and never spent the time to learn git tagging. You'll find what you need in [Release v1.0](https://github.com/bonsaiviking/NfSpy/releases/tag/v1.0)
