### ISSUE TITLE
fuse.FuseError: filesystem initialization failed

### ISSUE THREAD

**Issue by johackim** [bonsaiviking/NfSpy#4]
Hello,

I use python2.7 and i have an error when i run `nfspy` command : 

``` bash
root@f45244bad27d:/NfSpy# nfspy
fuse: missing mountpoint parameter
Traceback (most recent call last):
  File "/usr/local/bin/nfspy", line 4, in <module>
    main(NFSFuse)
  File "/usr/local/lib/python2.7/site-packages/nfspy/fusefs.py", line 63, in main
    return server.main()
  File "/usr/local/lib/python2.7/site-packages/nfspy/fusefs.py", line 14, in main
    return fuse.Fuse.main(self, *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/fuse.py", line 754, in main
    main(**d)
fuse.FuseError: filesystem initialization failed
```

I have install library fuse-python : `pip install fuse-python`

**Comment by nil0x42** [comment]
@bonsaiviking do you have an idea why this is happening ?

**Comment by noder45** [comment]
Did anyone figure this error out? Do you know how to fix this?

**Comment by ghost** [comment]
You need to provide parameters to the script, see `README.md`.

**Comment by bonsaiviking** [comment]
As the error message states, you are missing the mountpoint parameter. Try `nfspy --help` to see how to invoke it, or use `nfspysh` for an easier-to-use interface.
